### ISSUE TITLE
ROM Names Must Be <= 8 Characters on the SD Card

### ISSUE THREAD

**Issue by grantbreaksthings** [blazer82/gb.teensy#10]
Probably a limitation of the FAT32 library that we're using

**Comment by blazer82** [comment]
Yes, I noticed that, too. Should be mentioned in the documentation (as soon as there is one) and then that's fine.

**Comment by blazer82** [comment]
I documented this in the readme 112f431b50d8bc53484367b0d85eaa1d5877dc48
