### ISSUE TITLE
Power consumption?

### ISSUE THREAD

**Issue by lanmarc77** [blazer82/gb.teensy#18]
Hi,
really interesting project. May I ask how much power the breadboard version consumes?
With the original gameboy I was able to play around a day. How long would it be with this setup?

**Comment by blazer82** [comment]
Hi and thanks.

I actually never properly measured power consumption. That being said, without the audio part you should be able to run it with around 2 watts. Depending on the volume, the audio may take another couple of watts maybe.

With the same battery configuration as the original Gameboy had it would probably last no longer than 2-3 hours if I'm not mistaken.

**Comment by lanmarc77** [comment]
Hi and thank you for your answer.
If you go on with this project I think a unique feature (apart from the tech side having a DMG emulator for a µC) would be if the same runtime could be expected like from the original devices.
Assuming you do plan to put this in an original case you have 4 AA batteries. Maybe 15hours runtime (a day play minus sleep time) is a good start. Being a bit optimistic with the current we might get 3Wh from one of them resulting in 12Wh.
15hours then means 0.8W for the system. Is this even in the horizon of possible?

**Comment by blazer82** [comment]
You could always go for a Li-Po battery and probably get a lot more runtime out of it. I didn't do the math on this, though.

Also, I've kind of abandoned this project for its successor which will be running on an FPGA and will in fact be housed inside the original case. I don't know about its power usage yet, either.

**Comment by lanmarc77** [comment]
Ah what a pitty. Then good luck with the fpga version.
