### ISSUE TITLE
Document Wiring

### ISSUE THREAD

**Issue by blazer82** [blazer82/gb.teensy#5]
For better reproducibility document the wiring especially for buttons and sound output.

**Comment by grantbreaksthings** [comment]
Might want to start a GitHub Wiki for documentation

**Comment by blazer82** [comment]
I think I should be able to fit all into the readme. A wiki may be a good idea at a later point, though.

**Comment by blazer82** [comment]
Basic setup is now documented 112f431b50d8bc53484367b0d85eaa1d5877dc48
